Implement warning messages for invalid characters in names
homebridge/HAP-NodeJS pull request #1009
Opened 2023-06-27 23:51 UTC by NorthernMan54

## :recycle: Current situation

Invalid characters in names will trigger warning messages in the Home App. #1008 

## :bulb: Proposed solution

Implement warning messages for invalid characters in names

Sample warning messages

```
HAP-NodeJS WARNING: The service 'Play (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Play (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Pause (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Pause (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Skip Fwd (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Skip Fwd (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Skip Rev (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Skip Rev (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The accessory 'Spotify (Yamaha)' is getting published with the characteristic 'name' not following HomeKit naming rules ('Spotify (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
```

## :gear: Release Notes

Warning messages will now be logged for names containing invalid characters

## :heavy_plus_sign: Additional Information
*If applicable, provide additional context in this section.*

### Testing

Testing has been augmented with test cases for the various scenarios.

Output from testing with one of my plugins that has the issue.

```
HAP-NodeJS WARNING: The service 'Play (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Play (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Pause (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Pause (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Skip Fwd (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Skip Fwd (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The service 'Skip Rev (Yamaha)' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Skip Rev (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The accessory 'Spotify (Yamaha)' is getting published with the characteristic 'name' not following HomeKit naming rules ('Spotify (Yamaha)'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
```

### Reviewer Nudging

*Where should the reviewer start? what is a good entry point?*

@ebaauw @n0rt0nthec4t - Thanks for your input and feedback.  I have tried to include

2023-06-27 23:54 UTC, n0rt0nthec4t commented
This almost needs to be at the characteristic level. An example being if you have an accessory which uses the Characteristic.ConfiguredName, setting this for HomeKit with invalid characters shows an error in HomeKit.

2023-06-28 13:46 UTC, ebaauw reviewed
Looking good to me.

2023-06-28 13:49 UTC, ebaauw submitted a review, later dismissed

2023-06-28 13:49 UTC, ebaauw commented on src/lib/Accessory.spec.ts
> +      expect(consoleLogSpy).toHaveBeenCalledWith("HAP-NodeJS WARNING: The accessory 'Bad Name! 7430' is getting published with the characteristic 'Name' not following HomeKit naming rules ('Bad Name!
Or worse: it could cause the bridge that bridges this accessory to become unresponsive, incl. all other accessories bridged by this bridge.

2023-06-29 07:49 UTC, Supereg requested changes
Thanks for you work on this PR. 🚀

I think just allowing the base ASCII alphabet is maybe a bit restrictive?

2023-06-29 07:49 UTC, Supereg commented on package.json
> +  "version": "0.11.2",
Please don’t directly do the version bump in this PR.

2023-06-29 07:49 UTC, Supereg commented on src/lib/Accessory.spec.ts
> +
Thanks for all the tests 🚀

2023-06-29 07:49 UTC, Supereg commented on src/lib/Service.ts
> +  private checkName(name: string, value?: any) {
We duplicate the implementation here, do we? Maybe move it to a utility file?

2023-06-29 07:49 UTC, Supereg commented on src/lib/Accessory.ts
> +    const validHK = /^[a-zA-Z0-9\s'-.]+$/;   // Ensure only letter, numbers, apostrophe, or dash
How is HomeKit treating letters from different alphabets? I know we have a lot of international people. But even just looking at special characters like from the German or Swedish alphabet (ö, å, …)

They are all heavily used and HomeKit ist perfectly fine with those afaik.

Can we adjust this check to check for all Unicode letters (not sure though how HomeKit deals with e.g. the Chinese alphabet or if it just allows the Latin alphabet). E.g. refer to https://stackoverflow.com/a/62032796.

2023-06-30 02:00 UTC, NorthernMan54 commented on package.json
> +  "version": "0.11.2",
I have bumped this back

2023-06-30 02:01 UTC, NorthernMan54 commented on src/lib/Service.ts
> +  private checkName(name: string, value?: any) {
Moved to util/checkNames

2023-06-30 02:02 UTC, NorthernMan54 commented on src/lib/Accessory.ts
> +    const validHK = /^[a-zA-Z0-9\s'-.]+$/;   // Ensure only letter, numbers, apostrophe, or dash
This is going to take a bit more investigation

2024-06-23 00:58 UTC, donavanbecker approved these changes

2024-06-23 00:59 UTC, merged

2024-06-23 02:59 UTC, donavanbecker commented
@NorthernMan54 looks like the tests might be failing because of this? https://github.com/homebridge/HAP-NodeJS/actions/runs/9630265250/job/26560643569

2024-06-24 13:57 UTC, NorthernMan54 commented
If you look down the log, it is failing here -  ● Test suite failed to run

    src/lib/HAPServer.spec.ts:621:7 - error TS2578: Unused '@ts-expect-error' directive.

    621       // @ts-expect-error: type mismatch
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Something unrelated...

2024-07-29 05:30 UTC, NebzHB commented on src/lib/Accessory.ts
> +    const validHK = /^[a-zA-Z0-9\s'-.]+$/;   // Ensure only letter, numbers, apostrophe, or dash
Hi, I'm french and indeed i receive warnings for our accents, (é, à, è, ù, â, ê, î, ô, û)

2024-07-29 12:21 UTC, hjdhjd commented on src/lib/Accessory.ts
> +    const validHK = /^[a-zA-Z0-9\s'-.]+$/;   // Ensure only letter, numbers, apostrophe, or dash
> Hi, I'm french and indeed i receive warnings for our accents, (é, à, è, ù, â, ê, î, ô, û)

@NebzHB Please open an issue and provide the relevant details on which version of HAP-NodeJS you’re using. This feature has evolved substantially and unless you’re using HAP-NodeJS v1.0, you will encounter issues. Regardless - the best place to get support is to open an issue, not comment on a PR. It also provides a useful record for other users who may encounter similar problems.