v0.12.3
homebridge/HAP-NodeJS pull request #1042
Opened 2024-06-24 14:57 UTC by donavanbecker

## v0.12.3 (2024-06-24)

### Other Changes

- Implement warning messages for invalid characters in names (#1009) (@NorthernMan54)
- Mitigate event emitter "memory leak" warnings when a significant number of camera streaming events occur simultaneously (#1037) (@hjdhjd)
- Updated dependencies

2024-06-24 14:59 UTC, Shaquu commented
Wait for my change guys! 😅

2024-06-24 15:00 UTC, donavanbecker commented
> Wait for my change guys! 😅

will do.

2024-06-25 20:13 UTC, Shaquu requested changes

2024-06-25 20:13 UTC, Shaquu commented on CHANGELOG.md
> +## v0.12.3 (2024-06-24)
Date to be bumped :)

2024-06-25 20:15 UTC, bwp91 commented on CHANGELOG.md
> +## v0.12.3 (2024-06-24)
this line should be `BETA` until we release

2024-06-25 20:34 UTC, Shaquu commented on package.json
>    "dependencies": {
Would be nice to bump package `version` already

2024-06-25 20:39 UTC, bwp91 commented on package.json
>    "dependencies": {
which?

2024-06-25 20:48 UTC, Shaquu commented on package.json
>    "dependencies": {
Package, 0.12.2 to 0.12.3 or 0.12.3-whatever beta?

2024-06-25 20:51 UTC, bwp91 commented on package.json
>    "dependencies": {
this is set by the github actions to appropriate version if a beta or a release is being made

2024-06-25 20:52 UTC, bwp91 commented on package.json
>    "dependencies": {
if i haven’t answered your query please let me know!

2024-06-26 20:26 UTC, Shaquu commented
May I ask what is the plan with 0.12.3? Anything I could help with to boost this release?

2024-07-11 02:02 UTC, hjdhjd submitted a review, later dismissed

2024-07-11 02:11 UTC, hjdhjd approved these changes

2024-07-11 02:14 UTC, merged